---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    driver:
      network:
        - ["forwarded_port", {guest: 8443, host: 8443}]
        - ["forwarded_port", {guest: 443, host: 443}]
      customize:
        cpus: 2
        memory: 4096
    run_list:
      - recipe[chef_openshift::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
